{% set name = "scikit-cycling" %}
{% set version = "0.1.3" %}
{% set sha256 = "3acaed9ccfdfa34f43e75342bd86c18bb3ad4b940a24eedb78f674364fba1076" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/scikit-cycling/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - cython
    - numpy
    - llvm-openmp  # [osx]
  run:
    - python
    - scipy
    - {{ pin_compatible('numpy') }}
    - pandas
    - six
    - python-fitparse
    - joblib
    - scikit-learn
    - pandas <1

test:
  requires:
    - pytest <5
  imports:
    - skcycling
  commands:
    - pytest -l --pyargs skcycling -v -s

about:
  home: https://github.com/scikit-cycling/scikit-cycling
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A set of python modules for cyclist using powermeters.'

  description: |
    A set of python modules for cyclist using powermeters.
  doc_url: https://scikit-cycling.readthedocs.io/
  dev_url: https://github.com/scikit-cycling/scikit-cycling

extra:
  recipe-maintainers:
    - glemaitre
