# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangpython2.7
    - CONFIG=osx_c_compilerclangpython3.6
    - CONFIG=osx_c_compilerclangpython3.7
    - CONFIG=osx_c_compilertoolchain_cpython2.7
    - CONFIG=osx_c_compilertoolchain_cpython3.6
    - CONFIG=osx_c_compilertoolchain_cpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "WIwyxtEUwhcBo+rDZxMHRD5A9OJW4J+k987NcKufpklHSl9TNrYkPbE3mW51C9y6ttDtIhCABF87lRoGKAWOAqkAUzP43bkpOdxNY1LlDotws8gqQFQiL1ssrBRejsGy/y858PhbR1wrr40Am0fioWco4XnCt4HMh8CkmI55iXz0cYs8HY6IC/yGSzsADmJSTUt2UUbqkJWx076zLrf6G16rzCAFLG30ZZ1JEaXlALpyHZiaEyrN2f6VGgDibyPLbtYO7VqMuA5N61E8ulp9P3VqG3otOYc3bU8KdRcB3PBD/SGHvBuigbN2Fm/tgXRYfz9vXdUmT3OU9kQwnFkpaPRrY7ciV4B+vcTlCRlMsYH8KpJtkznQyeCBV/+W1DCxW7RM9n6QeJ9xJbPXTz9iFgioUOF3GemsqQcO91WBYtzfD0ukmsTt7+3OyZlwRMLQ/UTxaNspGCpa2tBQUFK2sI9oWDbY2J6bch3qJMrpnr1GvseEhds2+gdVkcVk4wnGeUXdPo2zX9RO5XhA3ZkiS98E9PEOzRB7MZPIQYegOPTPn2V8RvmBOyvEuJE0jKXsSfWHVtD3PlOabMd0cRtd0d+VfAJ2kXFZiB2PeArXBuO2ASmeS3SbIOY4L8Tkri7NRX77fOEuW+wwtnuoXlqOqx1NERoPa1n0yOU1fsqJWNg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
