travis:
  secure:
    BINSTAR_TOKEN: hbO0F/1TlXA4R02N+mKU9YUO0KPZ4RxvApBAw+s/tbZO1QTfTRCvzlPH/dN4QH0VrKjoLK2K0JsfmB+3a4lBa4kR+/v3ybtci72+Tg30YIxZjrbbT/4Gq+vH9qgEZaKddpZQlOsox5EEHwTKWwdHOVm/yff5ZvhiWm/fPOxZGAXW1Kw5uBT6h36UEhQZXk0hlFKYOvUqbRkyEr5ci4lFxA+9XS/2Izau8ELf8o6kSVecXq+gs2IQE4whrJ9ZVWmFe8hF7Bckk3xr0fxe3khlLRwJuQqHxmPYjedE1zBqjsXtEIMxqak0DGYRLByLQ9OmhVhJs9re8zBntwgiqUXNnluidKjFiQpFb7iqq7J/MCY1i6EXR8IhUil76az8aL4dgHMr5xiT+pxY2X0ArfEL1hhi+SFikH13eWYubozaiLkeIENzXfxtxokOaANQfx2fE/gMm8BXKpvWvo7763AbAEk2gvDBZTAqcJOycUzJEJoH5WU1sw4hGlmEO/L9q6GcoLiLyKVTdU0wIbKgza2cd4bXEmARp2n1il4jdX7SqPLfw7YHaOfRe0qGDSdNTPDAkpRzw4uuS5nSVeAhZjGxSow37gBkFgrz0zx5LrsnJBgY/BO1uXW2oOezRNmrRuDRqcWoEfw4bZd/aqfF02py0k8OMhlTA1y8c9uyYYnux94=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
