travis:
  secure:
    BINSTAR_TOKEN: WIwyxtEUwhcBo+rDZxMHRD5A9OJW4J+k987NcKufpklHSl9TNrYkPbE3mW51C9y6ttDtIhCABF87lRoGKAWOAqkAUzP43bkpOdxNY1LlDotws8gqQFQiL1ssrBRejsGy/y858PhbR1wrr40Am0fioWco4XnCt4HMh8CkmI55iXz0cYs8HY6IC/yGSzsADmJSTUt2UUbqkJWx076zLrf6G16rzCAFLG30ZZ1JEaXlALpyHZiaEyrN2f6VGgDibyPLbtYO7VqMuA5N61E8ulp9P3VqG3otOYc3bU8KdRcB3PBD/SGHvBuigbN2Fm/tgXRYfz9vXdUmT3OU9kQwnFkpaPRrY7ciV4B+vcTlCRlMsYH8KpJtkznQyeCBV/+W1DCxW7RM9n6QeJ9xJbPXTz9iFgioUOF3GemsqQcO91WBYtzfD0ukmsTt7+3OyZlwRMLQ/UTxaNspGCpa2tBQUFK2sI9oWDbY2J6bch3qJMrpnr1GvseEhds2+gdVkcVk4wnGeUXdPo2zX9RO5XhA3ZkiS98E9PEOzRB7MZPIQYegOPTPn2V8RvmBOyvEuJE0jKXsSfWHVtD3PlOabMd0cRtd0d+VfAJ2kXFZiB2PeArXBuO2ASmeS3SbIOY4L8Tkri7NRX77fOEuW+wwtnuoXlqOqx1NERoPa1n0yOU1fsqJWNg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
